apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: illustrations-poc
stringData:
  POSTGRES_USER: illustrator
  POSTGRES_PASSWORD: illustrator
  POSTGRES_DSN: postgresql://illustrator:illustrator@postgres.illustrations-poc.svc.cluster.local:5432/illustrations
